[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.25"
skip = ["src/periphery/ownable_2step.vy", "src/periphery/sweep.vy"]

[fmt]
single_line_statement_blocks = "single"
multiline_func_header = "params_first"
contract_new_lines = true
number_underscore = "thousands"
line_length = 120

[fuzz]
max_test_rejects = 50000000

remappings = [
    "@openzeppelin/=lib/openzeppelin-contracts/",
    "forge-std/=lib/forge-std/src/",
]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
