[project]
name = "flash-zapper"
version = "0.1.0"
description = "Smart contracts for leveraging up and down USDaf positions using a flash loan"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "vyper==0.4.1",
    "mamushi==0.0.4"
]

[tool.mamushi]
line-length = 200
safe = false